#!/bin/bash

volume=$(amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1)

sound=$(amixer get Master | tail -n 1 | awk '{print $NF}' | sed "s/\[//" | sed "s/\]//")


if [[ "$sound" == "on" ]];
then
    echo $volume
else
    echo Mute
    exit 33
fi
